// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKt11I86-rf8HLb0eRXlYC4AjrpOfSgn0',
    appId: '1:543545139335:web:174a413e3605e40b605822',
    messagingSenderId: '543545139335',
    projectId: 'travin-b131f',
    authDomain: 'travin-b131f.firebaseapp.com',
    storageBucket: 'travin-b131f.appspot.com',
    measurementId: 'G-BKNX9CEZ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlivvXf84GzrLd-k7KGOiyTjZ8qY148fk',
    appId: '1:543545139335:android:98ad4a6c9005313c605822',
    messagingSenderId: '543545139335',
    projectId: 'travin-b131f',
    storageBucket: 'travin-b131f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwpIzjwNnCr3PjbTdFO6YiHpNnuRsUsk',
    appId: '1:543545139335:ios:fb9d4026d1557b9f605822',
    messagingSenderId: '543545139335',
    projectId: 'travin-b131f',
    storageBucket: 'travin-b131f.appspot.com',
    iosBundleId: 'com.example.travIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAwpIzjwNnCr3PjbTdFO6YiHpNnuRsUsk',
    appId: '1:543545139335:ios:fb9d4026d1557b9f605822',
    messagingSenderId: '543545139335',
    projectId: 'travin-b131f',
    storageBucket: 'travin-b131f.appspot.com',
    iosBundleId: 'com.example.travIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKt11I86-rf8HLb0eRXlYC4AjrpOfSgn0',
    appId: '1:543545139335:web:9ceee37f7435f0c1605822',
    messagingSenderId: '543545139335',
    projectId: 'travin-b131f',
    authDomain: 'travin-b131f.firebaseapp.com',
    storageBucket: 'travin-b131f.appspot.com',
    measurementId: 'G-X3B7C2539G',
  );
}
